sudo: required
services:
    - docker

before_install:
    - sudo apt update
    - sudo apt install -y curl

install:
    - composer install
    - curl -s https://raw.githubusercontent.com/polonskiy/crowdr/master/crowdr > ~/crowdr
    - chmod +x ~/crowdr
    - sudo mv ~/crowdr /usr/local/bin/crowdr
    - crowdr build
    - crowdr run php 

before_script:
      - phpenv config-rm xdebug.ini

script:
    - crowdr exec php phpunit

after_success:
    - travis_retry crowdr exec php coveralls -v
