language: php
php:
    - '7.1'
sudo: required
services:
    - docker

before_install:
    - sudo apt update
    - sudo apt install -y curl

install:
    - composer install
    - curl -s https://raw.githubusercontent.com/polonskiy/crowdr/master/crowdr > ~/crowdr
    - chmod +x ~/crowdr
    - sudo mv ~/crowdr /usr/local/bin/crowdr
    - crowdr build
    - crowdr run curlwrapper

script:
    - crowdr exec curlwrapper phpunit
