sudo: required
services:
    - docker

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer install 
    - wget -O ~/crowdr https://raw.githubusercontent.com/polonskiy/crowdr/master/crowdr
    - chmod +x ~/crowdr
    - sudo mv ~/crowdr /usr/local/bin/crowdr
    - crowdr build
    - crowdr run php

script:
    - crowdr exec php phpunit

after_success:
    - travis_retry crowdr exec php coveralls -v
